Estetico.WebUI/Models/ErrorViewModel.cs
namespace Estetico.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Estetico.WebUI/Models/HomePageViewModel.cs
namespace Estetico.WebUI.Models
{
    public class HomePageViewModel
    {
        public HomePageViewModel()
        {
            Properties = new List<PropertyViewModel>();
        }

        public List<PropertyViewModel> Properties { get; set; }
    }
}

Estetico.WebUI/Models/PropertyViewModel.cs
namespace Estetico.WebUI.Models
{
    public class PropertyViewModel
    {
        public PropertyViewModel()
        {
            Name = String.Empty;
            Address = String.Empty;
        }
        
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string? Image { get; set; }
        public string Price { get; set; }
    }
}

Estetico.WebUI/Controllers/EstateController.cs
using Estetico.Data;
using Estetico.Data.Entities;
using Estetico.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace Estetico.WebUI.Controllers
{
    public class EstateController : Controller
    {
        private readonly ApplicationDbContext _DbContext;

        public EstateController(ApplicationDbContext dbContext)
        {
            _DbContext = dbContext;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SingleProperty(int ID)
        {
           Estate? estate = await _DbContext.Estates.FindAsync(ID);

            PropertyViewModel model = new PropertyViewModel()
            {
                Name = estate.Name,
                Address = "Villa Street, Key West, Miami",
                Image = estate.Image,
                Price = estate.Price.ToString("C"),
                ID = estate.ID
            };
            
            
            return View(model);
        }
    }
}

Estetico.WebUI/Controllers/HomeController.cs
using Estetico.Data;
using Estetico.Data.Entities;
using Estetico.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Estetico.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _dbContext;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var estates = _dbContext.Estates;

            HomePageViewModel homePageViewModel = new HomePageViewModel();

            foreach (Estate estate in estates)
            {
                PropertyViewModel propertyModel = new PropertyViewModel();
                propertyModel.ID = estate.ID;
                propertyModel.Price = estate.Price.ToString("C") + "/mo";
                propertyModel.Name = estate.Name;
                propertyModel.Address = "Villa Street, Key West, Miami";
                propertyModel.Image = estate.Image;

                homePageViewModel.Properties.Add(propertyModel);                             
            }

            return View(homePageViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
} 

Estetico.WebUI/Views/Shared/_Property.cshtml
@model PropertyViewModel

<div class="agents-grid" data-aos="fade-up" data-aos-delay="150">
    <div class="landscapes">
        <div class="project-single">
            <div class="project-inner project-head">
                <div class="homes">
                    <!-- homes img -->
                    <a href="single-property-1.html" class="homes-img">
                        <div class="homes-tag button alt featured">Featured</div>
                        <div class="homes-tag button alt sale">For Sale</div>
                        <div class="homes-price">@Model.Price</div>
                        <img src="@Model.Image" alt="home-1" class="img-responsive">
                    </a>
                </div>
                <div class="button-effect">
                    <a href="single-property-1.html" class="btn"><i class="fa fa-link"></i></a>
                    <a href="https://www.youtube.com/watch?v=14semTlwyUY" class="btn popup-video popup-youtube"><i class="fas fa-video"></i></a>
                    <a href="single-property-2.html" class="img-poppu btn"><i class="fa fa-photo"></i></a>
                </div>
            </div>
            <!-- homes content -->
            <div class="homes-content">
                <!-- homes address -->
                <h3><a asp-controller="Estate" asp-action="SingleProperty" asp-route-ID=@Model.ID>@Model.Name</a></h3>
                <p class="homes-address mb-3">
                    <a href="single-property-1.html">
                        <i class="fa fa-map-marker"></i><span>@Model.Address</span>
                    </a>
                </p>
                <!-- homes List -->
                <ul class="homes-list clearfix pb-0">
                    <li class="the-icons">
                        <i class="flaticon-bed mr-2" aria-hidden="true"></i>
                        <span>6 Bedrooms</span>
                    </li>
                    <li class="the-icons">
                        <i class="flaticon-bathtub mr-2" aria-hidden="true"></i>
                        <span>3 Bathrooms</span>
                    </li>
                    <li class="the-icons">
                        <i class="flaticon-square mr-2" aria-hidden="true"></i>
                        <span>720 sq ft</span>
                    </li>
                    <li class="the-icons">
                        <i class="flaticon-car mr-2" aria-hidden="true"></i>
                        <span>2 Garages</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>